name: Build for macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd react-native
          npm install
      
      - name: Fix Swift version conflict
        run: |
          cd react-native/ios
          # 统一设置 Swift 版本为 5.0
          sed -i '' 's/SWIFT_VERSION = 6.0/SWIFT_VERSION = 5.0/g' SwiftChat.xcodeproj/project.pbxproj || true
      
      - name: Install CocoaPods dependencies
        run: |
          cd react-native/ios
          pod install --repo-update
      
      - name: Build macOS app
        run: |
          cd react-native/ios
          xcodebuild \
            -workspace SwiftChat.xcworkspace \
            -scheme SwiftChat \
            -destination 'platform=macOS,variant=Mac Catalyst' \
            -configuration Release \
            -derivedDataPath ./build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.0 \
            clean build
      
      - name: Create DMG
        run: |
          cd react-native/ios
          APP_PATH=$(find ./build/Build/Products/Release-maccatalyst -name "SwiftChat.app" -type d | head -1)
          
          if [ -z "$APP_PATH" ]; then
            echo "Error: SwiftChat.app not found"
            exit 1
          fi
          
          echo "Found app at: $APP_PATH"
          mkdir -p dmg_temp
          cp -R "$APP_PATH" dmg_temp/
          
          hdiutil create -volname "SwiftChat" \
            -srcfolder dmg_temp \
            -ov -format UDZO \
            SwiftChat-macOS.dmg
          
          rm -rf dmg_temp
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwiftChat-macOS
          path: react-native/ios/SwiftChat-macOS.dmg
          retention-days: 30
